### ISSUE TITLE
Add a new interesting visualization

### ISSUE THREAD

**Issue by myname1111** [prathyvsh/lambda-calculus-visualizations#5]
I think you should add this visualization (https://veryunknown.com/post/lambda-calculus-visualized/), I think it's very interesting and unique and I don't think I've seen something like it before

**Comment by prathyvsh** [comment]
This is very similar to what I did here: https://x.com/prathyvsh/status/1260972217598271489

**Comment by prathyvsh** [comment]
This seems pretty similar to what I did here: https://x.com/prathyvsh/status/1260972217598271489

**Comment by prathyvsh** [comment]
This seems pretty similar to what I did here: https://x.com/prathyvsh/status/1260972217598271489

**Comment by myname1111** [comment]
Yeah, it kinda does. Both also seem to be pretty similar to [https://ima.udg.edu/~villaret/tilc/tilc.pdf](this). Should I close this issue?
